apiVersion: v2
name: traefik
version: 1.0.0
description: Traefik ingress controller with Gateway API support
dependencies:
  - name: traefik
    version: "34.3.0"
    repository: "https://traefik.github.io/charts"
